# from: https://game.ci/docs/
# targetPlatform values: https://docs.unity3d.com/ScriptReference/BuildTarget.html

name: Unity Build CI
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  # Build for Windows (32-Bit)
  build-win:
    name: Build Game for Windows
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        # ! Enable this if LFS is added
        # ! with:
        # !   lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      # Output
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-win
          path: build-win

  installer-win:
    name: Build Installer for Windows
    runs-on: windows-latest
    needs: build-win
    continue-on-error: true
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download Windows Build Artifact
      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-win
          path: build-win

      - name: Compile .iss to .exe Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Inno/inno.iss
          options: /O+

      # Output
      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: installer-win
          path: Inno/installer_win.exe

  # Build for MacOS
  build-macos:
    name: Build Game for MacOS
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        # ! Enable this if LFS is added
        # with:
        #   lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX

      # Output
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-macos
          path: build-macos
